fmt-check:
	@echo "custom fmt-check from makefile"
lint-static:
	@echo "custom lint-static from makefile"
build-debug:
	@echo "custom build-debug from makefile"
test-unit:
	@echo "custom test-unit from makefile"
test-integration:
	@echo "custom test-integration from makefile"
