name: Security Incident
description: Report a security vulnerability
labels: ["security"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the security vulnerability.
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What is the potential impact of this vulnerability?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the vulnerability.
    validations:
      required: true
  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have a suggestion on how to fix this?
