name: ci

on: [pull_request, push]

env:
  DWF_CACHE_ROOT: .cache/devflow

jobs:
  # ---------------------------------------------------------------------------
  # Phase 1 — Prep: resolve CI image, cache as tar for downstream jobs
  # ---------------------------------------------------------------------------
  prep:
    name: "Prep"
    runs-on: ubuntu-latest
    outputs:
      image_available: ${{ steps.check.outputs.available }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for Dockerfile.devflow
        id: check
        run: |
          if [ -f Dockerfile.devflow ]; then
            echo "available=true" >> $GITHUB_OUTPUT
          else
            echo "available=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.check.outputs.available == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker Layers
        if: steps.check.outputs.available == 'true'
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ hashFiles('Dockerfile.devflow') }}
          restore-keys: buildx-${{ runner.os }}-

      - name: Cache CI Image Tar
        if: steps.check.outputs.available == 'true'
        id: image_cache
        uses: actions/cache@v4
        with:
          path: ci-image.tar
          key: docker-ci-${{ hashFiles('Dockerfile.devflow') }}

      - name: Build CI Image (Buildx)
        if: steps.check.outputs.available == 'true' && steps.image_cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.devflow
          target: ci
          load: true
          tags: devflow-ci:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Save CI Image Tar
        if: steps.check.outputs.available == 'true' && steps.image_cache.outputs.cache-hit != 'true'
        run: |
          docker save -o ci-image.tar devflow-ci:latest
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache || true

  # ---------------------------------------------------------------------------
  # Phase 2 — Build: warm the cargo/sccache cache inside the CI container
  # Runs inside the CI container for shared filesystem and cache parity.
  # ---------------------------------------------------------------------------
  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v4

      - name: Restore CI Image Tar
        if: needs.prep.outputs.image_available == 'true'
        uses: actions/cache/restore@v4
        with:
          path: ci-image.tar
          key: docker-ci-${{ hashFiles('Dockerfile.devflow') }}

      - name: Load CI Image
        if: needs.prep.outputs.image_available == 'true'
        run: docker load -i ci-image.tar

      - name: Restore Cargo Cache
        uses: actions/cache@v4
        with:
          path: |
            .cargo-cache/registry
            .cargo-cache/git
            .cargo-cache/sccache
            target/ci
          key: cargo-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}-

      - name: Bootstrap & Warm Cache
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e CARGO_HOME=/workspace/.cargo-cache \
            -e CARGO_TARGET_DIR=/workspace/target/ci \
            -e SCCACHE_DIR=/workspace/.cargo-cache/sccache \
            -e RUSTC_WRAPPER=sccache \
            devflow-ci:latest \
            sh -c "cargo fetch && cargo build --all-targets"

      - name: Fix Cache Permissions
        if: always()
        run: sudo chmod -R a+rw .cargo-cache target/ci || true

  # ---------------------------------------------------------------------------
  # Phase 3 — Verify: sequential checks inside the same container instance
  # Restores the warmed cache from Phase 2 for zero-download execution.
  # ---------------------------------------------------------------------------
  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    needs: [prep, build]
    steps:
      - uses: actions/checkout@v4

      - name: Restore CI Image Tar
        if: needs.prep.outputs.image_available == 'true'
        uses: actions/cache/restore@v4
        with:
          path: ci-image.tar
          key: docker-ci-${{ hashFiles('Dockerfile.devflow') }}

      - name: Load CI Image
        if: needs.prep.outputs.image_available == 'true'
        run: docker load -i ci-image.tar

      - name: Restore Cargo Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .cargo-cache/registry
            .cargo-cache/git
            .cargo-cache/sccache
            target/ci
          key: cargo-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}-

      - name: Bootstrap Devflow
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e CARGO_HOME=/workspace/.cargo-cache \
            -e CARGO_TARGET_DIR=/workspace/target/ci \
            -e SCCACHE_DIR=/workspace/.cargo-cache/sccache \
            -e RUSTC_WRAPPER=sccache \
            devflow-ci:latest \
            sh -c "cargo install --path crates/devflow-cli --debug --root /workspace/.cargo-cache"

      - name: Run Sequential Checks
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e CARGO_HOME=/workspace/.cargo-cache \
            -e CARGO_TARGET_DIR=/workspace/target/ci \
            -e SCCACHE_DIR=/workspace/.cargo-cache/sccache \
            -e RUSTC_WRAPPER=sccache \
            -e IS_CONTAINER=true \
            -e PATH=/workspace/.cargo-cache/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
            devflow-ci:latest \
            sh -c "{{COMMANDS}}"

      - name: Fix Cache Permissions
        if: always()
        run: sudo chmod -R a+rw .cargo-cache target/ci || true
# project: {{PROJECT_NAME}}
