name: ci

on: [pull_request, push]

env:
  DWF_CACHE_ROOT: .cache/devflow

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v4
      - name: Restore DWF Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.DWF_CACHE_ROOT }}
          key: dwf-cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            dwf-cache-${{ runner.os }}-
      - name: Install Devflow
        run: curl -sL https://install.devflow.sh | bash
      - run: dwf build:debug

  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    needs: [prep, build]
    steps:
      - uses: actions/checkout@v4
      - name: Restore DWF Cache (Read-Only)
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DWF_CACHE_ROOT }}
          key: dwf-cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            dwf-cache-${{ runner.os }}-
      - name: Install Devflow
        run: curl -sL https://install.devflow.sh | bash
      - name: Run Sequential Checks
        run: |
{{COMMANDS}}
# project: {{PROJECT_NAME}}
